services:
  db:
    image: postgres:16
    container_name: service_db
    environment:
      POSTGRES_DB: service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: service_redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_web
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application -c gunicorn.conf.py"
    working_dir: /app/backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_celery
    command: celery -A core worker -l info
    working_dir: /app/backend
    volumes:
      - .:/app
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis
  
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service_celery_beat
    command: celery -A core beat -l info
    working_dir: /app/backend
    volumes:
      - .:/app
    env_file:
      - backend/.env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: