# Generated by Django 6.0.3 on 2026-06-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
